### ISSUE TITLE
Why for some value of integers, return String representation other then bytes directly.

### ISSUE THREAD

**Issue by yingbo** [jwhitbeck/java-rdb-parser#1]
In ZipList.java, ZipList::get(), why for integer encodings, it does:

`list.add(String.valueOf(v).getBytes(ASCII));` 

Can we just return bytes? Bytes is more consistent in all other parts of codes.

**Comment by jwhitbeck** [comment]
I'm not sure I understand the question. Do you mean why does it return `List<byte[]>` instead of `byte[]`?

**Comment by yingbo** [comment]
Sorry for confusion and didn't see your comments before. What I mean was like http://stackoverflow.com/questions/4485128/how-do-i-convert-long-to-byte-and-back-in-java. That is,

```
public byte[] longToBytes(long x) {
    ByteBuffer buffer = ByteBuffer.allocate(Long.BYTES);
    buffer.putLong(x);
    return buffer.array();
}

list.add(longToBytes(v))
```

**Comment by jwhitbeck** [comment]
AFAIK, the compact integer encoding is a trick that redis uses to use as little memory as possible. When communicating with clients (see the [redis protocol](http://redis.io/topics/protocol)), redis serializes integers as ascii bytes. This parser preserves that convention. Furthermore, this has the nice benefit of making all values printable for easy debugging. Otherwise, we would have to somehow indicate which byte arrays contain integers and which ones contain strings, thereby greatly complicating the API.

**Comment by yingbo** [comment]
Got it. Thank you, @jwhitbeck!
