### ISSUE TITLE
Cannot convert key in key-values redis

### ISSUE THREAD

**Issue by AnhLH19** [jwhitbeck/java-rdb-parser#5]
![image](https://user-images.githubusercontent.com/28858701/38493739-631088d4-3c1d-11e8-93dc-c3da839e93c0.png)
Here is the result . It's not convert correctly.

**Comment by jwhitbeck** [comment]
Hi,

This looks like an encoding issue, which java-rdb-parser is oblivious to (by design).

You seem to be trying out the example code. Have you tried replacing the ASCII encoding with something else?

**Comment by AnhLH19** [comment]
Dear,
I using redisTemplate and jedis to push data into redis cache and trying parse data to string , which many ways but it's seem return 1 one result like that, But i'm using post man to test the result it's work perfectly. And i also try remove ASCII encoding but it isn't work
![image](https://user-images.githubusercontent.com/28858701/38496519-1429c43c-3c28-11e8-923b-30dbd763ca2f.png)

**Comment by jwhitbeck** [comment]
Thanks for the added context. Taking a closer look at what you are reading from redis, it appears that your redisTemplate framework is writing serialized java objects to redis (see the `java/lang/String` that is getting prefixed to some values) rather than plain strings. 

java-rdb-parser is working as expected and returning the raw serialized bytes of the java objects. To decode them you might have to wrap the returned byte arrays with something like:

```java
new ObjectInputStream(new ByteArrayInputStream(value)).readObject()
```

**Comment by AnhLH19** [comment]
It's worked. Thank's for your response . It's make me have a deep look about redis. Wish you have a nice days
Respects,
